# Generated by Django 6.0.5 on 2026-05-25 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PopularRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_city', models.CharField(max_length=100, verbose_name='Откуда')),
                ('to_city', models.CharField(max_length=100, verbose_name='Куда')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Популярный маршрут',
                'verbose_name_plural': 'Популярные маршруты',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('price_per_km', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена за км (руб)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название автомобиля')),
                ('photo', models.ImageField(blank=True, upload_to='cars/', verbose_name='Фото')),
                ('extra_price_per_km', models.DecimalField(decimal_places=2, default=0, help_text='Добавляется к базовой ставке тарифа', max_digits=8, verbose_name='Доп. цена за км (руб)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='catalog.tariff', verbose_name='Тариф')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='RoutePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена (руб)')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='catalog.popularroute', verbose_name='Маршрут')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_prices', to='catalog.tariff', verbose_name='Тариф')),
            ],
            options={
                'verbose_name': 'Цена маршрута',
                'verbose_name_plural': 'Цены маршрутов',
                'unique_together': {('route', 'tariff')},
            },
        ),
    ]
