# Generated by Django 6.0.5 on 2026-05-25 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_address', models.TextField(verbose_name='Откуда')),
                ('to_address', models.TextField(verbose_name='Куда')),
                ('trip_datetime', models.DateTimeField(verbose_name='Дата и время поездки')),
                ('need_docs', models.BooleanField(default=False, verbose_name='Отчётные документы')),
                ('distance_km', models.PositiveIntegerField(default=0, verbose_name='Расстояние (км)')),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Примерная стоимость (руб)')),
                ('fio', models.CharField(max_length=300, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=30, verbose_name='Телефон')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('accepted', 'Принята'), ('in_progress', 'В пути'), ('completed', 'Завершена'), ('cancelled', 'Отменена')], db_index=True, default='new', max_length=20, verbose_name='Статус')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки оператора')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата заявки')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='catalog.car', verbose_name='Автомобиль')),
                ('tariff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='catalog.tariff', verbose_name='Тариф')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
    ]
