upstream backend {
    server backend:8000;
}

server {
    listen 80;
    server_name parkmaximum.ru www.parkmaximum.ru 5.35.84.172;

    client_max_body_size 20M;
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml text/javascript;
    gzip_min_length 1024;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    include /etc/nginx/includes/app.conf;
}
